CREATE FUNCTION PROMEDIOCOSTO(@VAL_REF INT)
RETURNS DECIMAL (10,2)
BEGIN
	DECLARE @PROM DECIMAL (10,2)
	SELECT @PROM = AVG(VAL_COSTO_INV)
	FROM INVENTARIO
	WHERE VAL_COSTO_INV >= @VAL_REF
	RETURN @PROM
END

SELECT DBO.PROMEDIOCOSTO (5000) AS "PROMEDIO DE COSTO"