IF OBJECT_ID('MIPROMEDIO')IS NOT NULL
BEGIN
	DROP FUNCTION DBO.MIPROMEDIO /*SI EXISTIA LA DBO, ELIMINARLA*/
END

/*CREAR LA FUNCIÓN*/
CREATE FUNCTION MIPROMEDIO(@VALOR1 INT, @VALOR2 INT)
RETURNS DECIMAL (10,2) /*10 DIGITOS, DE LOS CUALES 2 SERÁN DE LA PARTE DECIMAL*/
AS
BEGIN
	DECLARE @RESULTADO DECIMAL (10,2)
	SET @RESULTADO = (@VALOR1 + @VALOR2)/2.0
	RETURN @RESULTADO

END

SELECT DBO.MIPROMEDIO (6,4) AS "PROMEDIO"

DECLARE @N1 INT = 6, @N2 INT = 4
PRINT 'EL PROMEDIO DE ' + CAST(@N1 AS CHAR (2)) + 'Y ' + CAST (@N2 AS CHAR (2)) + 'ES: ' + CAST(DBO.MIPROMEDIO (@N1,@N2) AS CHAR (10))

