USE DROGUERIA5
GO
CREATE PROCEDURE INGRESAR_PROV
@NIT_PROV NCHAR (15), 
@NOM_PROV NCHAR (50),
@TEL_PROV NCHAR (20),
@CEL_PROV NCHAR (20),
@DIR_PROV NCHAR (100),
@FEC_ING_PROV DATETIME
AS
BEGIN
	INSERT INTO PROVEEDORES
	VALUES (@NIT_PROV, @NOM_PROV, @TEL_PROV, @CEL_PROV, @DIR_PROV, @FEC_ING_PROV)
END