CREATE TABLE AUDITORIALIBROS
(
	ID INT IDENTITY PRIMARY KEY,
	FECHA DATETIME NULL, 
	CODIGO INT NOT NULL,
	TITULO VARCHAR (50) NULL,
	AUTOR VARCHAR (50) NULL,
	PRECIO DECIMAL (6,2) NULL,
	STOCK INT NULL,
	OPERACION VARCHAR (3) NULL
		CHECK(OPERACION = 'INS' OR OPERACION = 'DEL')

)