IF NOT EXISTS (SELECT * FROM sys.databases WHERE NAME = 'DB_TEST') /*SI NO EXISTE ESA BASE DE DATOS, CREARLA*/
BEGIN
	CREATE DATABASE DB_TEST
END
GO
USE DB_TEST

IF NOT EXISTS (SELECT * FROM sys.sysobjects WHERE NAME = 'EXPEDIENTES' AND xtype = 'U')
BEGIN 
	CREATE TABLE EXPEDIENTES
	(
		CODIGO VARCHAR(15) NOT NULL,
		ESTADO VARCHAR(20) DEFAULT 'INICIO',
		FECHACAMBIOESTADO DATETIME,
		PRIMARY KEY (CODIGO)
	)
END

INSERT INTO EXPEDIENTES (CODIGO) VALUES ('EXP1')
INSERT INTO EXPEDIENTES (CODIGO) VALUES ('EXP2')
INSERT INTO EXPEDIENTES (CODIGO) VALUES ('EXP3')

IF NOT EXISTS (SELECT * FROM sys.sysobjects WHERE name = 'HISTORICOESTADOEXPEDIENTE' and xtype = 'U') /*U = USUARIO*/
BEGIN
	CREATE TABLE HISTORICOESTADOEXPEDIENTE
	(
		ID INT IDENTITY,
		CODIGO VARCHAR (15) NOT NULL,
		ESTADO VARCHAR (20) NOT NULL,
		FECHA DATETIME DEFAULT GETDATE() /*FECHA DEL SISTEMA*/
		PRIMARY KEY (ID)
	)
END

IF OBJECT_ID ('TRIGGEFECHAESTADO', 'TR') IS NOT NULL /*TR: TIPO TRIGGER*/
BEGIN 
	DROP TRIGGER TRIGGEFECHAESTADO
END
GO

/*pendiente crear el trigger*/

CREATE TRIGGER TRIGGERFECHACAMBIOESTADO
ON EXPEDIENTES
AFTER UPDATE
AS 
IF UPDATE (ESTADO)
BEGIN
	UPDATE EXPEDIENTES
	SET FECHACAMBIOESTADO = GETDATE()
	WHERE CODIGO = (SELECT CODIGO FROM inserted)

	INSERT INTO HISTORICOESTADOEXPEDIENTE (CODIGO, ESTADO)
	(SELECT CODIGO, ESTADO
	 FROM deleted
	 WHERE CODIGO = deleted.CODIGO)
END