CREATE VIEW DATOS_MEDICAMENTOS
AS
SELECT PK_REF_INV AS "REFERENCIA",
	   DESC_INV AS "DESCRIPCIÓN",
	   STOCK_INV AS "STOCK",
	   VAL_COSTO_INV AS "VALOR DE COSTO",
	   VAL_VENTA_INV AS "VALOR DE VENTA",
	   NOM_MARCA AS "MARCA"
	   NOM_TIPO AS "TIPO"
FROM INVENTARIO, MARCA, TIPO
WHERE FK_ID_MARCA_INV = PK_ID_MARCA AND
	  FK_ID_TIPO_INV = PK_ID_TIPO