DECLARE @REFERENCIA NCHAR (15),
		@DESCRIPCION NCHAR (50),
		@STOCK INT

DECLARE DESCARGA_STOCK CURSOR FOR 
SELECT PK_REF_INV, DESC_INV, STOCK_INV
FROM INVENTARIO

OPEN DESCARGA_STOCK

FETCH NEXT FROM DESCARGA_STOCK INTO @REFERENCIA, @DESCRIPCION, @STOCK
WHILE @@FETCH_STATUS = 0
BEGIN
	IF @STOCK >= 350
	BEGIN
		PRINT TRIM(@REFERENCIA) + ' - ' + TRIM(@DESCRIPCION)
		PRINT 'STOCK ANTERIOR: ' + TRIM(STR(@STOCK))
		PRINT 'STOCK DESPUÉS: ' + TRIM(STR(@STOCK-40))
		UPDATE INVENTARIO SET STOCK_INV = STOCK_INV-40
		WHERE PK_REF_INV = @REFERENCIA
END
ELSE /*SI NO ES >= 350*/
BEGIN
	PRINT TRIM(@REFERENCIA) + ' - ' + TRIM(@DESCRIPCION)
	PRINT 'STOCK NO MODIFICADO: ' + TRIM(STR(@STOCK))
END	

	PRINT '---------------------------------------------------'
	FETCH NEXT FROM DESCARGA_STOCK INTO @REFERENCIA, @DESCRIPCION, @STOCK

END

CLOSE DESCARGA_STOCK
DEALLOCATE DESCARGA_STOCK