/*MOSTRAR COMO SE PUEDE MOVER LA LECTURA DE LA LINEA (ADELANTAR O RETROCEDER), SE PUEDE POSICIONAR EN DIFERENTES DIRECCIONES*/

DECLARE @NOMBRE NCHAR(50)

DECLARE NOMBRES CURSOR SCROLL FOR /*SCROLL ES LA CARACTERÍSTICA QUE PERMITE DESPLAZAR HACIA ARRIBA O ABAJO*/
SELECT NOM_CLI FROM CLIENTES

OPEN NOMBRES

FETCH NEXT FROM NOMBRES INTO @NOMBRE
PRINT @NOMBRE
FETCH NEXT FROM NOMBRES INTO @NOMBRE
PRINT @NOMBRE
FETCH RELATIVE -1 FROM NOMBRES INTO @NOMBRE
PRINT @NOMBRE
FETCH PRIOR FROM NOMBRES I
INTO @NOMBRE
PRINT @NOMBRE
FETCH RELATIVE 2 FROM NOMBRES INTO @NOMBRE
PRINT @NOMBRE

CLOSE NOMBRES
DEALLOCATE NOMBRES