USE DROGUERIA5
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE CUENTA_FACTURAS
@CED_CLI NCHAR(20),
@CANTIDAD INT OUTPUT 
AS
BEGIN 
	SET @CANTIDAD = 
	(
	SELECT COUNT (*)
	FROM CLIENTES, ENC_FAC
	WHERE PK_CED_CLI = FK_CED_CLI_FAC AND
		PK_CED_CLI = @CED_CLI
	GROUP BY PK_CED_CLI
	)
END


/*******************************Llamado al procedimiento almacenado.****************************************/
DECLARE @CANTIDAD INT
EXEC CUENTA_FACTURAS '45897896', @CANTIDAD OUTPUT
SELECT @CANTIDAD AS "CANTIDAD FACTURAS"