CREATE TABLE CLIENTES
(
PK_CEDULA NCHAR (15) ,
NOMBRE VARCHAR (15),
TELEFONO NCHAR (10) NULL,
CELULAR NCHAR (10) NOT NULL,
DIRECCION VARCHAR (20) NOT NULL,
FECHA_REGISTRO DATETIME
CONSTRAINT CEDULA PRIMARY KEY (PK_CEDULA)
)

CREATE TABLE PROVEEDORES
(
PK_NIT NCHAR (15),
NOMBRE_PROVEEDOR VARCHAR (50),
TELEFONO NCHAR (10),
CELULAR NCHAR(10),
DIRECCION VARCHAR (20),
FECHA_INGRESO DATETIME,
CONSTRAINT NIT PRIMARY KEY (PK_NIT)
)
