USE MASTER
GO

CREATE DATABASE SEGUIMIENTO_2
GO

USE SEGUIMIENTO_2

CREATE TABLE CLIENTES
(
	PK_ID_CLIENTE INT,
	DIRECCION_ENVIO NCHAR(100),
	SALDO_CLIENTE DECIMAL(10,2),
	LIMITE_CREDITO DECIMAL(10,2),
	DESCUENTO DECIMAL(4,2),

	CONSTRAINT PK_DE_CLIENTE PRIMARY KEY(PK_ID_CLIENTE)

)

CREATE TABLE FABRICA
(
	PK_ID_FABRICA INT IDENTITY,
	NOMBRE_FABRICA NCHAR(100),
	TELEFONO_FABRICA NCHAR(10),
	ARTICULOS_PROVEE INT,

	CONSTRAINT PK_DE_FABRICA PRIMARY KEY(PK_ID_FABRICA)

)

CREATE TABLE ARTICULOS
(
	PK_ID_ARTICULO INT IDENTITY,
	FK_ID_FABRICA INT,
	STOCK_FABRICA NCHAR(100),
	DESCRIPCION NCHAR (100),

	CONSTRAINT PK_DE_ARTICULO PRIMARY KEY(PK_ID_ARTICULO),

	CONSTRAINT FK_PROVEEDOR FOREIGN KEY (FK_ID_FABRICA)
	REFERENCES FABRICA(PK_ID_FABRICA)

)

CREATE TABLE PEDIDOS
(
	PK_ID_PEDIDO INT IDENTITY,
	FK_ID_FABRICA INT,
	FK_ID_CLIENTE INT,
	FK_ID_ARTICULO INT,
	FECHA_PEDIDO DATE,

	CONSTRAINT PK_DE_PEDIDO PRIMARY KEY(PK_ID_PEDIDO),

	CONSTRAINT FK_FABRICA FOREIGN KEY(FK_ID_FABRICA)
	REFERENCES FABRICA(PK_ID_FABRICA),

	CONSTRAINT FK_CLIENTE FOREIGN KEY(FK_ID_CLIENTE)
	REFERENCES CLIENTES(PK_ID_CLIENTE),

	CONSTRAINT FK_ARTICULO FOREIGN KEY(FK_ID_ARTICULO)
	REFERENCES ARTICULOS(PK_ID_ARTICULO)

)	